title:              Bits of math
email:              lenseswaenen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing bits of mathematics that I've come across in my ~10 years as a professional mathematical engineer.
author:             Lense Swaenen
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
twitter_username: LenseSwaenen
github_username:  lenseswaenen
facebook_username:
instagram_username:
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# SEO settings
twitter:
  username: LenseSwaenen
  card: summary_large_image

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
  - github-pages
